# Concepts for Diagonalization of strain

This notebook showcases how diagonalization of strain works.

## Finding the transformation matrix

Creating the fictitous strain $e$ for $c_{46}$

In [1]:
import numpy
from cij.util import c_

key = c_(15)

e = numpy.zeros((3, 3))

e[key.i[0] - 1, key.i[1] - 1] = 1
e[key.i[1] - 1, key.i[0] - 1] = 1

e[key.j[0] - 1, key.j[1] - 1] = 1
e[key.j[1] - 1, key.j[0] - 1] = 1

print(e)

[[1. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]]


The transformation matrix $T$ is the column-wise eigenvectors of the strain matrix $e$

In [2]:
evals, T = numpy.linalg.eig(e)
print(T)

[[ 0.85065081 -0.52573111  0.        ]
 [ 0.          0.          1.        ]
 [ 0.52573111  0.85065081  0.        ]]


The $e'$ in the rotated coordinate system is the matrix with eigenvalues of $e$ in its diagonals

In [3]:
print(numpy.diag(evals))

[[ 1.61803399  0.          0.        ]
 [ 0.         -0.61803399  0.        ]
 [ 0.          0.          0.        ]]


We can retrive the original strain with

$$
e' = T^{-1} e T
$$

or backwards

$$
e = T e' T^{-1}
$$

In [4]:
print("e' = ")
print(T.T @ e @ T)

print("e' = T^{-1} e T:", numpy.allclose(numpy.diag(evals), T.T @ e @ T))

print("e = ")
print(T @ numpy.diag(evals) @ T.T)

print("e = T e' T^{-1}:", numpy.allclose(e, T @ numpy.diag(evals) @ T.T))

e' = 
[[ 1.61803399e+00  1.11022302e-16  0.00000000e+00]
 [ 1.66533454e-16 -6.18033989e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
e' = T^{-1} e T: True
e = 
[[ 1.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00 -5.55111512e-17]]
e = T e' T^{-1}: True


## Testing with symbols

In [5]:
import sympy

def round_expr(expr, num_digits=4):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sympy.Number)})

In [6]:
a = sympy.symbols("e_11")
b = sympy.symbols("e_22")
c = sympy.symbols("e_33")

m = sympy.Matrix([
    [a, 0, 0],
    [0, b, 0],
    [0, 0, c]
])

round_expr(T.T @ m @ T)

Matrix([
[ 0.7236*e_11 + 0.2764*e_33, -0.4472*e_11 + 0.4472*e_33,        0],
[-0.4472*e_11 + 0.4472*e_33,  0.2764*e_11 + 0.7236*e_33,        0],
[                         0,                          0, 1.0*e_22]])

In [7]:
a = sympy.symbols("α")
b = sympy.symbols("β")
c = sympy.symbols("γ")

m = sympy.Matrix([
    [1 + a, 0.   , 0.   ],
    [0.   , 1 + b, 0.   ],
    [0.   , 0.   , 1 + c]
])

round_expr(T.T @ m @ T)

Matrix([
[0.7236*α + 0.2764*γ + 1.0,      -0.4472*α + 0.4472*γ,           0],
[     -0.4472*α + 0.4472*γ, 0.2764*α + 0.7236*γ + 1.0,           0],
[                        0,                         0, 1.0*β + 1.0]])

In [36]:
import itertools
from cij.util import C_


def _meke_symbol(*argv):
    key = c_("".join(str(i+1) for i in argv))
    return sympy.symbols("c_%d%d" % key.v)

def get_strain_energy(fictitious_strain: numpy.ndarray):
    
    s = 0
      
    nz = numpy.nonzero(fictitious_strain)

    for (i, j), (k, l) in itertools.product(zip(*nz), zip(*nz)):
        e1 = fictitious_strain[i,j]
        e2 = fictitious_strain[k,l]
        c = _meke_symbol(i,j,k,l)
        s += c * e1 * e2
    
    return s

In [37]:
e_prime = numpy.diag(evals)
round_expr(get_strain_energy(e_prime))

2.618*c_11 - 2.0*c_12 + 0.382*c_22

In [38]:
round_expr(get_strain_energy(e))

1.0*c_11 + 4.0*c_15 + 4.0*c_55