# Concepts for Diagonalization of strain

This notebook showcases how diagonalization of strain works.

## Finding the transformation matrix

Creating the fictitous strain $e$ for $c_{46}$

In [1]:
import numpy
from cij.util import c_

key = c_(44)

e = numpy.zeros((3, 3))

e[key.i[0] - 1, key.i[1] - 1] = 1
e[key.i[1] - 1, key.i[0] - 1] = 1

e[key.j[0] - 1, key.j[1] - 1] = 1
e[key.j[1] - 1, key.j[0] - 1] = 1

print(e)

[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


The transformation matrix $T$ is the column-wise eigenvectors of the strain matrix $e$

In [2]:
evals, T = numpy.linalg.eig(e)
print(T)

[[ 0.          0.          1.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.70710678 -0.70710678  0.        ]]


The $e'$ in the rotated coordinate system is the matrix with eigenvalues of $e$ in its diagonals

In [3]:
print(numpy.diag(evals))

[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]


We can retrive the original strain with

$$
e' = T^{-1} e T
$$

or backwards

$$
e = T e' T^{-1}
$$

In [4]:
print("e' = ")
print(T.T @ e @ T)

print("e' = T^{-1} e T:", numpy.allclose(numpy.diag(evals), T.T @ e @ T))

print("e = ")
print(T @ numpy.diag(evals) @ T.T)

print("e = T e' T^{-1}:", numpy.allclose(e, T @ numpy.diag(evals) @ T.T))

e' = 
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
e' = T^{-1} e T: True
e = 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
e = T e' T^{-1}: True


## Testing with symbols

In [5]:
import sympy

def round_expr(expr, num_digits=4):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sympy.Number)})

In [6]:
a = sympy.symbols("e_11")
b = sympy.symbols("e_22")
c = sympy.symbols("e_33")

m = sympy.Matrix([
    [a, 0, 0],
    [0, b, 0],
    [0, 0, c]
])

round_expr(T.T @ m @ T)

Matrix([
[0.5*e_22 + 0.5*e_33, 0.5*e_22 - 0.5*e_33,        0],
[0.5*e_22 - 0.5*e_33, 0.5*e_22 + 0.5*e_33,        0],
[                  0,                   0, 1.0*e_11]])

In [7]:
a = sympy.symbols("α")
b = sympy.symbols("β")
c = sympy.symbols("γ")

m = sympy.Matrix([
    [1 + a, 0.   , 0.   ],
    [0.   , 1 + b, 0.   ],
    [0.   , 0.   , 1 + c]
])

round_expr(T.T @ m @ T)

Matrix([
[0.5*β + 0.5*γ + 1.0,       0.5*β - 0.5*γ,           0],
[      0.5*β - 0.5*γ, 0.5*β + 0.5*γ + 1.0,           0],
[                  0,                   0, 1.0*α + 1.0]])